version: 2
jobs:
  build:
    docker:
      - image: circleci/rust

    steps:
      - checkout

      - run:
          name: Install llvm
          command: sudo apt-get install llvm

      - run:
          name: Test
          command: cargo test

      - run:
          name: Build
          command: cargo build

