version: 2
jobs:
  build:
    docker:
      - image: circleci/rust

    steps:
      - checkout

      - run:
          name: Install homebrew
          command: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

      - run:
          name: Install LLVM-7
          command: brew install llvm@7 && export PATH="/usr/local/opt/llvm@7/bin:$PATH"

      - run:
          name: Test
          command: cargo test

      - run:
          name: Build
          command: cargo build --release

