version: 2
jobs:
  build:
    docker:
      - image: circleci/rust

    steps:
      - checkout

      - run: brew install llvm@7 && export PATH="/usr/local/opt/llvm@7/bin:$PATH"

      - run:
          name: Test
          command: cargo test

      - run:
          name: Build
          command: cargo build --release

